{% set name = "python-crfsuite" %}
{% set version = "0.9.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 6eff965ca70567396d822c9a35ea74b0f7edb27d9471524997bdabe7a6da5f5a

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  skip: True  # [py<38]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools >=42
    - wheel
    - cython
  run:
    - python

test:
  requires:
    - pytest
    - pip
    - conda-build
  source_files:
    - tests
  imports:
    - pycrfsuite
    - pycrfsuite._logparser
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests

about:
  home: https://github.com/scrapinghub/python-crfsuite
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python binding for CRFsuite
  description: |
    python-crfsuite is a python binding to CRFsuite.
  doc_url: https://python-crfsuite.readthedocs.io
  dev_url: https://github.com/scrapinghub/python-crfsuite

extra:
  recipe-maintainers:
    - wyseguy7
    - ericdill
    - rmax
    - mcs07
