{% set name = "python-crfsuite" %}
{% set version = "0.9.12" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-', '_') }}-{{ version }}.tar.gz
  sha256: db37fccc3bd8f0c49c28a7697ca79c89d67b3fd5bf119122866169240ac4c480

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  skip: true  # [py<310]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - python
    - pip
    - setuptools >=42
    - wheel
    - cython
  run:
    - python

test:
  requires:
    - pytest
    - pip
  source_files:
    - tests
  imports:
    - pycrfsuite
    - pycrfsuite._logparser
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests

about:
  home: https://github.com/scrapinghub/python-crfsuite
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python binding for CRFsuite
  description: |
    python-crfsuite is a python binding to CRFsuite.
  doc_url: https://python-crfsuite.readthedocs.io
  dev_url: https://github.com/scrapinghub/python-crfsuite

extra:
  recipe-maintainers:
    - wyseguy7
    - ericdill
    - rmax
    - mcs07
