travis:
  secure:
    BINSTAR_TOKEN: KdbLTMqbP0brYLfUm5dzKTJqPUdctz9MWD5eX1Pu4mZmhxNx/zAdki8n3H7fBnyZCDjZfO8h8pRa1ELhf0wmJhMPbqe2YrSuHdo+fEL48fYmK01INlkeLhCvbjK5GyEksu5Wqpv8x5qEqhcXwm/Rzy5TJrHEaW1kLls+n1lCReDSoTyGxDatfFd4VdW9EEvzhFYfWnEayqCT9ZXJiJbRX1Rmxt1eaY9SnyYxDLpNhN7JWgKHEAyc13Zm/Jv7qbR5bO40JN4PCkBXw8K3NZXcJyN69hA69zfiaTSXU5Aali3Fg4MKQ6a7WFMm8DeoctFayZX7wzDWWE8bqOYSeJqvTyu2/Eg9MLS4x2ayVMrGDoqInzVkcwf8dbmE7EZ9kUwEjwdGfJhVOs331IhG97HElF3vkOmNkYOVvLPwpF11xi69naAEtZHLdc7Jse1RaB1NI3X8VyEgpDq4MEQOHV3lNgSVhzzPSXcC9b9Jq+D5bAQyLfp+PrPM+M9JZfTiAUm/EZwBs3w+6x+uo0ZETVz4g3HliPReXLTLRdiLlOb1pm9g68Te0AIo5mCFYv2L5J0EUkX40R5YWmkua5mKnIUkxtU8v/nVuFGeyZwpX/Ow/eYo7cyDQbkXffptIQQ0jIAm0qPETHLtI5rCWUr1HCG0UfQay9takJ+Huj59KpjvtwA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
