travis:
  secure:
    BINSTAR_TOKEN: TNqKuy558lhjskUYFJ1HEaH+ZX1+O+plkvzU1ysFe3SsTcoeyct/NlNeN34bxPAUECjH0DcpMvLwdfIY09uQahOxt8XQ4z/Q3u4kmN6b3TUkSjYdfMGqp0BK1ljfYnpTOAFlDxeyzE/a97MzbA2FDWHISENiPfADBXw8PiD6QfeHCaFtsdIFIh8KK9+jQSFWhFnxfpYnNPi/c86sWo1g8D+oT6iiIomM+tQqTSvN500Hx1TRBKrQ86s4GSWRSS5AWlvyih00sdTzrdTKg7L//rjQgeQxIX7KuFPuj/sZQZB2RzX8EpBNETaUXLm5LzZk8l8n38oBVBXdQT3onTukVLs2RTyaFMlU9DSik7Aq3gHE0chO/xGfgI5Gfc97+biQGvKubNXb91CVoajv8MYAoJT0dHIYZqeR8B6CIYDVuYiRyDKgZVYHCcUTQs7qj4Ye30cs7tUa5T12RJ+N+f+/pktAJ2x/NCHP6EZcg5g9JWLFWqlwP7OcLCgnqwfPmrAhdYMGmvYOPzVvTRzRdapkbE3Lk1jDAf54g0vmfdWOVgt+Vye3TTG+fb7D8Fdv//gdj/tOf1jeR5NU39VOws2aBsVdGu7cF9YwihUd1K7QkVd9nbih+zNK1/fpkDEuUYPOmUqUibvlo9hy9YRlXxTLTCzL/EpaPOW7zYBHUoiNhr4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
