travis:
  secure:
    BINSTAR_TOKEN: pu0IJciD4yOqLrECDJs6a0hqXPqFzpHvG0EDBaYZyiyB5bsEgrGfn3EJeguo0vemF3zVO+jHmRE2gG90hpPjBlE547w/qDa/7g80rXb3qASANkoGt8oKcvs7vV6LtA1ZI590GyfhcUxMpTCMYR82Kz/u7tQ1aUqUrH/fiOeottf7ozL5NnUimq//9XFNP9B+0juTexrfR7+BkQ7TSp8QhNX63y36HTjCORAa/55tKzXuoZ1MYwq54+d1ekxsMcIzdbd2BL50yQYkyVy7pH4ceE+Onr90GDYLs2VzoJUf2+QAGSU7E5AcQIQDSl1F11VEZneiPE+wRlRSkDfSoe/Pvbu5w8tKlkdg+3ogCZ7ccxraALDAdjJ4/4SfwzxlrK6S5UwnbhSFyXviLWW5Y8nihIlW6AQL1X/fYV1vBOAN7Ii7gsOrj12eCe65o26SMq0ZQT3kptKJ1K+rj1y/TrTB9JXFRH4w1u5Bb8CLCFUtz5pcG3OnHLfYPeNerl96gze2q+NvDsim9/oRA0Tm4jUULbeSv3UvnauZLZLr04jPbp2J6F/6E5Th/dL7ioiz4PAcLTzMohN9zXjfXUoe8mndxX9P2Ze3AuE7JAPYIPmTep8ZOm7qvOUN2UeSPSMLefn5hFLNvy8G5oTzTVIoyf7TdzXxQGc9e3AMRVyfbIGzkkM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
